apiVersion: v1
kind: Pod
metadata:
  name: busybox-filesystem
spec:
  containers:
  - name: busybox
    image: busybox:1.32.0
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: node-host
      mountPath: /node-host
  volumes:
  - name: node-host
    hostPath:
      path: /
      type: Directory
